name: Run HKO Tracker

on:
  repository_dispatch:
    types: [trigger-every-10-min]
  workflow_dispatch:
    inputs:
      custom_action:
        description: 'Action for Custom Warning'
        type: choice
        options:
          - NONE (Run Auto Check Only)
          - ISSUE
          - EXTEND
          - CANCEL
        default: 'NONE (Run Auto Check Only)'
      warning_type:
        description: 'Custom Warning Type'
        type: choice
        options:
          - White Rainstorm Warning
          - Blue Rainstorm Warning
          - Red Rainstorm Watch
          - Black Rainstorm Watch
          - Severe Thunderstorm Emergency
      valid_until:
        description: 'Valid Until Time (e.g., 19:30)'
        type: string
        required: false
      area:
        description: 'Area (For Emergency)'
        type: choice
        options:
          - None
          - Kowloon
          - Outlying Islands
          - West NT
          - East NT
          - HK Island
      red_chance:
        description: 'Red Rainstorm Chance (e.g., 40%. Type CLEAR to remove)'
        type: string
        required: false
      black_chance:
        description: 'Black Rainstorm Chance (e.g., 10%. Type CLEAR to remove)'
        type: string
        required: false

permissions:
  contents: write
  actions: write

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-noto-cjk

    - name: Install Python Dependencies
      run: pip install requests pillow

    - name: Run script
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        CUSTOM_ACTION: ${{ github.event.inputs.custom_action }}
        CUSTOM_TYPE: ${{ github.event.inputs.warning_type }}
        CUSTOM_VALID_UNTIL: ${{ github.event.inputs.valid_until }}
        CUSTOM_AREA: ${{ github.event.inputs.area }}
        RED_CHANCE: ${{ github.event.inputs.red_chance }}
        BLACK_CHANCE: ${{ github.event.inputs.black_chance }}
      run: python bot.py

    - name: Save Updated Warning State Permanently
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add warning_state.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update warning state [skip ci]" && git push)
